spring:
  jpa:
    hibernate:
      dll-auto: none;
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5452/filedb
    username: postgres
    password:
    
server:
    port: 8081
    servlet:
        context-path: /service